/**
 * Permission catalog mirroring the backend `PermissionDefinition` enum
 * (D:\TKD_Van_Quan\ai-receptionist-web-be-java\src\main\java\com\dat\ai_receptionist_web\enums\Security\PermissionDefinition.java).
 *
 * Synced: 2026-09-12
 * Keep names EXACTLY equal to the backend contract. If the backend adds or
 * renames a permission, update this file and the sync test
 * (`./permissions.sync.test.ts`) will detect the drift when the backend repo is
 * available.
 *
 * Future goal: generate this file from the backend OpenAPI/contract instead of
 * mirroring by hand.
 */
export const Permission = {
  BRANCH_READ: 'BRANCH_READ',
  BRANCH_CREATE: 'BRANCH_CREATE',
  BRANCH_UPDATE: 'BRANCH_UPDATE',
  BRANCH_DELETE: 'BRANCH_DELETE',

  PERSON_READ: 'PERSON_READ',
  PERSON_CREATE: 'PERSON_CREATE',
  PERSON_UPDATE: 'PERSON_UPDATE',
  PERSON_DELETE: 'PERSON_DELETE',

  POSITION_READ: 'POSITION_READ',
  POSITION_CREATE: 'POSITION_CREATE',
  POSITION_UPDATE: 'POSITION_UPDATE',
  POSITION_DELETE: 'POSITION_DELETE',

  USER_PERSON_READ: 'USER_PERSON_READ',
  USER_PERSON_CREATE: 'USER_PERSON_CREATE',
  USER_PERSON_UPDATE: 'USER_PERSON_UPDATE',
  USER_PERSON_DELETE: 'USER_PERSON_DELETE',

  CLASS_SCHEDULE_READ: 'CLASS_SCHEDULE_READ',
  CLASS_SCHEDULE_CREATE: 'CLASS_SCHEDULE_CREATE',
  CLASS_SCHEDULE_UPDATE: 'CLASS_SCHEDULE_UPDATE',
  CLASS_SCHEDULE_DELETE: 'CLASS_SCHEDULE_DELETE',

  COURSE_READ: 'COURSE_READ',
  COURSE_CREATE: 'COURSE_CREATE',
  COURSE_UPDATE: 'COURSE_UPDATE',
  COURSE_DELETE: 'COURSE_DELETE',

  COURSE_PRICE_READ: 'COURSE_PRICE_READ',
  COURSE_PRICE_CREATE: 'COURSE_PRICE_CREATE',
  COURSE_PRICE_UPDATE: 'COURSE_PRICE_UPDATE',
  COURSE_PRICE_DELETE: 'COURSE_PRICE_DELETE',

  WALLET_READ: 'WALLET_READ',
  WALLET_CREATE: 'WALLET_CREATE',
  WALLET_UPDATE: 'WALLET_UPDATE',
  WALLET_DELETE: 'WALLET_DELETE',

  WALLET_TRANSACTION_READ: 'WALLET_TRANSACTION_READ',
  WALLET_TRANSACTION_CREATE: 'WALLET_TRANSACTION_CREATE',
  WALLET_TRANSACTION_UPDATE: 'WALLET_TRANSACTION_UPDATE',
  WALLET_TRANSACTION_DELETE: 'WALLET_TRANSACTION_DELETE',

  COURSE_PURCHASE_READ: 'COURSE_PURCHASE_READ',
  COURSE_PURCHASE_CREATE: 'COURSE_PURCHASE_CREATE',
  COURSE_PURCHASE_UPDATE: 'COURSE_PURCHASE_UPDATE',
  COURSE_PURCHASE_DELETE: 'COURSE_PURCHASE_DELETE',

  FITNESS_READ: 'FITNESS_READ',
  FITNESS_CREATE: 'FITNESS_CREATE',
  FITNESS_UPDATE: 'FITNESS_UPDATE',
  FITNESS_DELETE: 'FITNESS_DELETE',

  FITNESS_RECORD_READ: 'FITNESS_RECORD_READ',
  FITNESS_RECORD_CREATE: 'FITNESS_RECORD_CREATE',
  FITNESS_RECORD_UPDATE: 'FITNESS_RECORD_UPDATE',
  FITNESS_RECORD_DELETE: 'FITNESS_RECORD_DELETE',

  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATION_CREATE: 'NOTIFICATION_CREATE',
  NOTIFICATION_UPDATE: 'NOTIFICATION_UPDATE',
  NOTIFICATION_DELETE: 'NOTIFICATION_DELETE',

  NOTIFICATION_RECIPIENT_READ: 'NOTIFICATION_RECIPIENT_READ',
  NOTIFICATION_RECIPIENT_CREATE: 'NOTIFICATION_RECIPIENT_CREATE',
  NOTIFICATION_RECIPIENT_UPDATE: 'NOTIFICATION_RECIPIENT_UPDATE',
  NOTIFICATION_RECIPIENT_DELETE: 'NOTIFICATION_RECIPIENT_DELETE',

  AUTH_SESSION_READ: 'AUTH_SESSION_READ',
  AUTH_SESSION_CREATE: 'AUTH_SESSION_CREATE',
  AUTH_SESSION_UPDATE: 'AUTH_SESSION_UPDATE',
  AUTH_SESSION_DELETE: 'AUTH_SESSION_DELETE',

  PERMISSION_READ: 'PERMISSION_READ',
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',
  PERMISSION_DELETE: 'PERMISSION_DELETE',

  ROLE_READ: 'ROLE_READ',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',

  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',

  CLASS_SESSION_READ: 'CLASS_SESSION_READ',
  CLASS_SESSION_CREATE: 'CLASS_SESSION_CREATE',
  CLASS_SESSION_UPDATE: 'CLASS_SESSION_UPDATE',
  CLASS_SESSION_DELETE: 'CLASS_SESSION_DELETE',

  COURSE_STAFF_ASSIGNMENT_READ: 'COURSE_STAFF_ASSIGNMENT_READ',
  COURSE_STAFF_ASSIGNMENT_CREATE: 'COURSE_STAFF_ASSIGNMENT_CREATE',
  COURSE_STAFF_ASSIGNMENT_UPDATE: 'COURSE_STAFF_ASSIGNMENT_UPDATE',
  COURSE_STAFF_ASSIGNMENT_DELETE: 'COURSE_STAFF_ASSIGNMENT_DELETE',

  COACH_TIMESHEET_READ: 'COACH_TIMESHEET_READ',
  COACH_TIMESHEET_CREATE: 'COACH_TIMESHEET_CREATE',
  COACH_TIMESHEET_UPDATE: 'COACH_TIMESHEET_UPDATE',
  COACH_TIMESHEET_DELETE: 'COACH_TIMESHEET_DELETE',

  BELT_EXAM_READ: 'BELT_EXAM_READ',
  BELT_EXAM_CREATE: 'BELT_EXAM_CREATE',
  BELT_EXAM_UPDATE: 'BELT_EXAM_UPDATE',
  BELT_EXAM_DELETE: 'BELT_EXAM_DELETE',

  LEAVE_REQUEST_READ: 'LEAVE_REQUEST_READ',
  LEAVE_REQUEST_CREATE: 'LEAVE_REQUEST_CREATE',
  LEAVE_REQUEST_UPDATE: 'LEAVE_REQUEST_UPDATE',
  LEAVE_REQUEST_DELETE: 'LEAVE_REQUEST_DELETE',

  SESSION_ATTENDANCE_READ: 'SESSION_ATTENDANCE_READ',
  SESSION_ATTENDANCE_CREATE: 'SESSION_ATTENDANCE_CREATE',
  SESSION_ATTENDANCE_UPDATE: 'SESSION_ATTENDANCE_UPDATE',
  SESSION_ATTENDANCE_DELETE: 'SESSION_ATTENDANCE_DELETE',

  STUDENT_ENROLLMENT_READ: 'STUDENT_ENROLLMENT_READ',
  STUDENT_ENROLLMENT_CREATE: 'STUDENT_ENROLLMENT_CREATE',
  STUDENT_ENROLLMENT_UPDATE: 'STUDENT_ENROLLMENT_UPDATE',
  STUDENT_ENROLLMENT_DELETE: 'STUDENT_ENROLLMENT_DELETE',

  WALLET_TOP_UP_CREATE: 'WALLET_TOP_UP_CREATE',
  WALLET_REFUND_CREATE: 'WALLET_REFUND_CREATE',
} as const satisfies Record<string, string>;

export type PermissionValue =
  (typeof Permission)[keyof typeof Permission];

export const PERMISSION_VALUES: readonly PermissionValue[] = Object.values(
  Permission,
);
